name: Build

on:
  push:
    paths:
      - '*.c'
      - 'Android.mk'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build DirtyCow
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: $ANDROID_NDK/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk APP_ABI=armeabi-v7a APP_PLATFORM=android-17

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: CVE-2016-5195
          path: libs/armeabi-v7a/*
