name: Build

on:
  push:
    paths:
      - '*.c'
      - 'Android.mk'
  workflow_dispatch:

jobs:
  build:
    name: Build DirtyCow
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
          local-cache: true

      - name: Build
        run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk APP_ABI=armeabi-v7a APP_PLATFORM=android-17

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: CVE-2016-5195_CT1
          path: libs/armeabi-v7a/*
